use_frameworks!

pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'ASIHTTPRequest'
target 'joyfortSdkLib_Example' do
  pod 'joyfortSdkLib', :path => '../'
  
  
  target 'joyfortSdkLib_Tests' do
    inherit! :search_paths

    
  end
end
