//
//  JoyfortConfig.h
//  Test
//
//  Created by godfery on 15/6/25.
//  Copyright (c) 2015年 joyfort. All rights reserved.
//

#ifndef Test_JoyfortConfigIp_h
#define Test_JoyfortConfigIp_h

FOUNDATION_EXPORT  NSString *const LOGIN_URL_IP ;

FOUNDATION_EXPORT  NSString *const CREATE_USER_IP ;

FOUNDATION_EXPORT NSString *const LOGIN_TOKEN_URL_IP ;

FOUNDATION_EXPORT NSString *const PAY_URL_IP;

FOUNDATION_EXPORT NSString *const IOS_PAY_URL_IP ;

FOUNDATION_EXPORT NSString *const SERVERLIST_URL_IP ;


FOUNDATION_EXPORT NSString *const IS_BIND_URL_IP ;

FOUNDATION_EXPORT NSString *const BIND_URL_IP ;

FOUNDATION_EXPORT NSString *const PLAY_LOG_URL_IP ;

FOUNDATION_EXPORT NSString *const VERSION_CHECK_URL_IP ;
//参数配置读取
FOUNDATION_EXPORT NSString *const PARAM_URL_IP ;
//mycard auth code
FOUNDATION_EXPORT NSString *const MYCARD_AUTHCODE_IP ;

FOUNDATION_EXPORT NSString *const MYCARD_PAY_URL_IP ;

FOUNDATION_EXPORT NSString *const PAYPAL_PAY_URL_IP ;


//---------cache
FOUNDATION_EXPORT NSString *const BIND_CACHE_URL_IP ;
FOUNDATION_EXPORT NSString *const  LOGIN_CACHE_URL_IP ;
FOUNDATION_EXPORT NSString *const  REVOKE_BIND_CACHE_URL_IP ;

FOUNDATION_EXPORT NSString *const  IS_BIND_CACHE_URL_IP ;

FOUNDATION_EXPORT NSString *const CREATE_USER_CACHE_IP ;
FOUNDATION_EXPORT NSString *const SWITCH_LOGIN_URL_IP ;



//ios openid replace

FOUNDATION_EXPORT NSString *const  LOGIN_CACHE_URL_IP_IOS ;

FOUNDATION_EXPORT NSString *const  SWITCH_LOGIN_URL_UPDATE_IP_IOS ;
FOUNDATION_EXPORT NSString *const  IS_BIND_CACHE_URL_UPDATE_IP_IOS ;
FOUNDATION_EXPORT NSString *const  REVOKE_BIND_CACHE_URL_UPDATE_IP_IOS ;
FOUNDATION_EXPORT NSString *const  BIND_CACHE_URL_UPDATE_IP_IOS ;
FOUNDATION_EXPORT NSString *const  CREATE_USER_CACHE_UPDATE_IP_IOS ;
#endif
