//
//  JoyfortConfig.h
//  Test
//
//  Created by godfery on 15/6/25.
//  Copyright (c) 2015年 joyfort. All rights reserved.
//

#ifndef Test_JoyfortConfig_h
#define Test_JoyfortConfig_h

FOUNDATION_EXPORT NSString *const KEY_USER_NAME;

FOUNDATION_EXPORT const int RETRY_COUNT;


FOUNDATION_EXPORT NSString *const SECRET ;
FOUNDATION_EXPORT NSString *const LOGIN_URL;
FOUNDATION_EXPORT NSString *const CREATE_USER;
FOUNDATION_EXPORT NSString *const LOGIN_TOKEN_URL ;

FOUNDATION_EXPORT NSString *const PAY_URL ;

FOUNDATION_EXPORT NSString *const IOS_PAY_URL;

FOUNDATION_EXPORT NSString *const SERVERLIST_URL ;



FOUNDATION_EXPORT NSString *const IS_BIND_URL ;

FOUNDATION_EXPORT NSString *const BIND_URL ;

FOUNDATION_EXPORT NSString *const PLAY_LOG_URL ;

FOUNDATION_EXPORT NSString *const VERSION_CHECK_URL;
//参数配置读取
FOUNDATION_EXPORT NSString *const PARAM_URL ;
//mycard auth code
FOUNDATION_EXPORT NSString *const MYCARD_AUTHCODE ;

FOUNDATION_EXPORT NSString *const MYCARD_PAY_URL ;

FOUNDATION_EXPORT NSString *const PAYPAL_PAY_URL ;


//缓存相关
FOUNDATION_EXPORT NSString *const JOYFORT_LOGIN_CACHE_KEY ;



FOUNDATION_EXPORT NSString *const JOYFORT_SHARE_KEY ;

FOUNDATION_EXPORT NSString *const  JOYFORT_SHARE_UID ;

FOUNDATION_EXPORT NSString *const  JOYFORT_SHARE_TOKEN ;

FOUNDATION_EXPORT NSString *const JOYFORT_SHARE_USER_JSON ;


FOUNDATION_EXPORT NSString *const BIND_CACHE_URL;
FOUNDATION_EXPORT NSString *const  LOGIN_CACHE_URL ;
FOUNDATION_EXPORT NSString *const  REVOKE_BIND_CACHE_URL ;
FOUNDATION_EXPORT NSString *const  IS_BIND_CACHE_URL ;

FOUNDATION_EXPORT NSString *const CREATE_USER_CACHE;
FOUNDATION_EXPORT NSString *const SWITCH_LOGIN_URL;

FOUNDATION_EXPORT NSString *const JOYFORT_SYNC_DNS_URL;
FOUNDATION_EXPORT NSString *const JOYFORT_SYNC_IP_URL;
FOUNDATION_EXPORT NSTimeInterval  JOYFORT_SYNC_IP_TIME_INTERVAL ;


FOUNDATION_EXPORT  NSString *const  LOGIN_CACHE_URL_IOS ;

FOUNDATION_EXPORT NSString *const  SWITCH_LOGIN_URL_UPDATE_IOS ;
FOUNDATION_EXPORT NSString *const  IS_BIND_CACHE_URL_UPDATE_IOS ;
FOUNDATION_EXPORT NSString *const  REVOKE_BIND_CACHE_URL_UPDATE_IOS ;
FOUNDATION_EXPORT NSString *const  BIND_CACHE_URL_UPDATE_IOS ;
FOUNDATION_EXPORT NSString *const  CREATE_USER_CACHE_UPDATE_IOS ;


#endif
